id: IBF8DD19B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:29:34+00:00'
last_modified: '2022-06-10T05:54:14.147747+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28811
  title: གཞི་ལམ་འབྲས་བུའི་སྨོན་ལམ་གྱི་དོན་གསལ་བར་བྱེད་པ་ཀུན་ཏུ་བཟང་པོའི་ཞལ་ལུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FD49:
      image_group_id: I4646
      title: ''
      total_pages: 132
      order: 1
      base_file: FD49.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
